### ISSUE TITLE
about use_class_balancing

### ISSUE THREAD

**Issue by aguang1201** [brucechou1983/CheXNet-Keras#10]
I setted about use_class_balancing=true.But the result is bad.Is not in the multi-task case,class_balancing should not be used?Thanks.

**Comment by brucechou1983** [comment]
@aguang1201 

You're right. This option doesn't provide any improvement if you're using default setting. Actually that's one of the algorithms I tried, and I keep that in the repo as an example of how users can design their own class weights. Thanks for trying it and raising the problem.
