### ISSUE TITLE
is test_cam.py not completed? 

### ISSUE THREAD

**Issue by aguang1201** [brucechou1983/CheXNet-Keras#11]
I find the test_cam.py in develop branch, but not in master branch.And test_cam.py in develop have error in code.The test_cam.py is not completed,right?

**Comment by taoyilee** [comment]
Hi
Apologies for the delay, a working version of CAM will be committed by next week. It is temporarily removed for verification and testing. We are super these weeks due to Chinese new year.

**Comment by aguang1201** [comment]
@taoyilee 
Thank you.
Happy Chinese new year.
And gou nian wang wang wang   :D

**Comment by taoyilee** [comment]
Hi there, 
CAM code is ready now, @brucechou1983  would you mind combine the PR from #13. Thank you.

**Comment by brucechou1983** [comment]
#16 is merged. Close issue.

**Comment by aguang1201** [comment]
wow.Great.Thank you.
