### ISSUE TITLE
how about mean and std

### ISSUE THREAD

**Issue by aguang1201** [brucechou1983/CheXNet-Keras#17]
The mean and std which you are using in the image preprocessing is the mean and std in imagenet. Imagenet is training with RGB images.But x-ray image is gray image.So how to set the mean and std in chexnet?Thank you.

**Comment by brucechou1983** [comment]
@aguang1201 

I asked the original paper author about the same question. He replicates the gray scale image along the RGB channels, which is exactly what I did in the source code.
