### ISSUE TITLE
Prediction Accuracy seem to be not accurate

### ISSUE THREAD

**Issue by sriniwaas** [brucechou1983/CheXNet-Keras#22]
Looking at the GradCam output, most of the test samples seem to wrongly predicted. 

## GradCam output of gradcam_1502.jpg:

** y_hat[1502] = [0.14673501 0.01134805 0.12639914 0.24252617 0.5742752  0.58539766
0.19411625 0.8418181  0.28799048 0.11468869 0.86016876 0.35104084 0.4047146  0.07352768]
** y[1502] = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
** Label/Prediction: Normal/Emphysema

<img width="1025" alt="screen shot 2018-03-01 at 7 04 49 am" src="https://user-images.githubusercontent.com/8960467/36827278-9b0ddda8-1d38-11e8-82a8-1aebbf31cd99.png">

**Comment by sriniwaas** [comment]
@brucechou1983 : Am I making some mistake ? 

This is my following mean AUROC over times of solution:

(epoch#1) auroc: 0.6054178808410038, lr: 0.0010000000474974513
(epoch#2) auroc: 0.6153898515525261, lr: 0.0010000000474974513
(epoch#3) auroc: 0.7197292204745015, lr: 0.0010000000474974513
(epoch#4) auroc: 0.727417806869657, lr: 0.0010000000474974513
(epoch#5) auroc: 0.7361441755050312, lr: 0.0010000000474974513
(epoch#6) auroc: 0.7572797132956085, lr: 0.0010000000474974513
(epoch#8) auroc: 0.7798043960885578, lr: 0.00010000000474974513
(epoch#9) auroc: 0.7802407395160709, lr: 0.00010000000474974513
(epoch#10) auroc: 0.7829573867178824, lr: 0.00010000000474974513
(epoch#11) auroc: 0.7846305339997773, lr: 0.00010000000474974513
(epoch#13) auroc: 0.7877435868538029, lr: 0.00010000000474974513
(epoch#15) auroc: 0.7877899214441385, lr: 1.0000000656873453e-05
(epoch#16) auroc: 0.7898826172439825, lr: 1.0000000656873453e-05
(epoch#18) auroc: 0.7947169140993289, lr: 1.0000000656873453e-05
(epoch#29) auroc: 0.7947727550860314, lr: 1.000000082740371e-07

Dump of Epoch 29:
<img width="700" alt="screen shot 2018-03-01 at 10 13 18 am" src="https://user-images.githubusercontent.com/8960467/36827429-8292df66-1d39-11e8-882e-6008b9e26bc6.png">

**Comment by sriniwaas** [comment]
Pls. provide your inputs

**Comment by ZJkerry** [comment]
Hello
Could you tell me why I get the fallow following error,when test ? Thank you.
"Found 0 images belonging to 0 classes." 
 "Traceback (most recent call last):
  File "test.py", line 128, in <module>
    main()
  File "test.py", line 94, in main
    x, y = load_generator_data(test_generator, step_test, len(class_names))
  File "/home/zj/tf_example/CheXNet-Keras-master/callback.py", line 22, in load_generator_data
    batch_x, batch_y = next(generator)
  File "/home/zj/tf_example/CheXNet-Keras-master/generator.py", line 26, in custom_image_generator
    for batch_x, batch_y in iterator:
  File "/home/zj/CheXNet-keras-py3.6/lib/python3.6/site-packages/keras/preprocessing/image.py", line 833, in __next__
    return self.next(*args, **kwargs)
  File "/home/zj/CheXNet-keras-py3.6/lib/python3.6/site-packages/keras/preprocessing/image.py", line 1185, in next
    index_array = next(self.index_generator)
  File "/home/zj/CheXNet-keras-py3.6/lib/python3.6/site-packages/keras/preprocessing/image.py", line 818, in _flow_index
    current_index = (self.batch_index * self.batch_size) % self.n
ZeroDivisionError: integer division or modulo by zero"

**Comment by apollo-time** [comment]
I am got the same low accuracy.
What is different with https://github.com/arnoweng/CheXNet?

**Comment by brucechou1983** [comment]
@sriniwaas Please try 0.3.0 and see if that solve your problem.

@apollo-time arnoweng's project is implemented in PyTorch.

**Comment by brucechou1983** [comment]
@sriniwaas Please note that this is a multi-label problem. The output stage is NOT a softmax function, and you have to find the threshold for best prediction performance for each of the classes. High area under ROC only guarantee that you could find a threshold that does the job pretty well. It doesn't tell you that you're model is accurate enough when you set the threshold as 0.5.

**Comment by sriniwaas** [comment]
@brucechou1983 Agree with your observation. Couldn't check, on this, as i was OOO (no internet). Will check on this in a couple of days and shall post.

**Comment by taewookim** [comment]
NOt sure but @arnoweng's pytorch version of chexnet pretty much bombed on every test

https://github.com/arnoweng/CheXNet/issues/11

**Comment by Theophylline** [comment]
@taewookim did you use images from the same dataset?

**Comment by paulwababu** [comment]
@sriniwaas , could you share your code on predicting on new images?
