### ISSUE TITLE
Add CAM capability

### ISSUE THREAD

**Issue by taoyilee** [brucechou1983/CheXNet-Keras#4]
recommendation: Grad-CAM
[https://github.com/ramprs/grad-cam](https://github.com/ramprs/grad-cam)
[https://github.com/jacobgil/keras-cam](https://github.com/jacobgil/keras-cam)
[https://github.com/jacobgil/keras-grad-cam](https://github.com/jacobgil/keras-grad-cam)

**Comment by taoyilee** [comment]
Here it is, try this #7 

- [Add Guided backprop]

**Comment by mongoose54** [comment]
@taoyilee Thanks for adding that! 

It is giving me errors though in lines [64](https://github.com/brucechou1983/CheXNet-Keras/blob/develop/test_cam.py#L64)  and [72](https://github.com/brucechou1983/CheXNet-Keras/blob/develop/test_cam.py#L72) for undeclared `fx_prob` and `nm_prob` variables.

**Comment by taoyilee** [comment]
Hi
Apologies for the delay, a working version of CAM will be committed by next week. It is temporarily removed for verification and testing.

**Comment by brucechou1983** [comment]
#16
