### ISSUE TITLE
Pre trained model weights?

### ISSUE THREAD

**Issue by taewookim** [brucechou1983/CheXNet-Keras#6]
Anyone have the weights as downloadable file?

**Comment by brucechou1983** [comment]
The pretrained model weights file is from [DenseNet-Keras](https://drive.google.com/open?id=0Byy2AcGyEVxfSTA4SHJVOHNuTXc).

**Comment by taewookim** [comment]
Thanks @brucechou1983 

how about the final output_weights? Anyone have that as a downloadable by any chance?

**Comment by brucechou1983** [comment]
If you are talking about the initial weights for the custom output stage, you don't really need that for transfer learning. If you are asking for a fully trained model, I would share that after training on better selected sets. I planned to make that available in early Feb.

**Comment by taewookim** [comment]
how can i help expedite that? and how do u determine if the selected set is better?

**Comment by brucechou1983** [comment]
You are more than welcome to share the way you split the dataset.

**Comment by brucechou1983** [comment]
@taewookim The file is ready. Please find the link in readme.

**Comment by WrathofBhuvan11** [comment]
unable to load pretrained weights,

densenet = tf.keras.applications.DenseNet121(
include_top=False,
weights="CheXNet_Keras_0.3.0_weights.h5",
input_shape=(224,224,3)
)
https://stackoverflow.com/questions/64390544/unable-to-load-chexnet-pre-trained-weight-file-to-densenet121
ValueError: You are trying to load a weight file containing 242 layers into a model with 241 layers.

**Comment by faizaHafiz** [comment]
> The pretrained model weights file is from [DenseNet-Keras](https://drive.google.com/open?id=0Byy2AcGyEVxfSTA4SHJVOHNuTXc).

Do you have weights file for model with 241 layers
