### ISSUE TITLE
Add ResNet and GoogLeNet support

### ISSUE THREAD

**Issue by taoyilee** [brucechou1983/CheXNet-Keras#8]
Benchmarking different NNs

**Comment by billhhh** [comment]
@taoyilee Bruce's code is written in a pretty well manner, simply modify model/densenet121.py to the model what you like~~

**Comment by taoyilee** [comment]
Just adding a ticket for this to remind myself. 
Already working on my proposal :+1:

**Comment by brucechou1983** [comment]
#24
