### ISSUE TITLE
Got MemoryError while training

### ISSUE THREAD

**Issue by hmchuong** [brucechou1983/CheXNet-Keras#9]
I've used a Google Cloud with 2 x NVIDIA Tesla K80 (12GB for each), 16 vCPUs, 16 GB memory. 
I've trained with batch_size=32 and 16 but always got MemoryError. Can I know what is the best computer requirements for training?

**Comment by brucechou1983** [comment]
I use one 1080ti (11gb) + 64gb ram, batch_size=32 works fine under this setting. K80 should be no prob. Looks like you need to trade off memory and speed.
